apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: alpine:3.18
      script: |
        #!/bin/sh
        echo "Cleaning up workspace..."
        rm -rf /workspace/output/*

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test-task
spec:
  steps:
    - name: run-nose-tests
      image: python:3.9
      script: |
        #!/bin/sh
        pip install nose
        nosetests
